/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guicelsiusfahrenheit;

import java.text.ParseException;
import javax.swing.JOptionPane;

/**
 *
 * @author Alec
 */
public class CelsiusFarhenheit extends javax.swing.JFrame {

    /**
     * Creates new form CelsiusFarhenheit
     */
    public CelsiusFarhenheit() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtTemperatureField = new javax.swing.JTextField();
        lblEnterTemperature = new javax.swing.JLabel();
        lblTemperatureConverted = new javax.swing.JLabel();
        btnCalculate = new javax.swing.JButton();
        btnSwap = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtTemperatureField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTemperatureFieldActionPerformed(evt);
            }
        });

        lblEnterTemperature.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        lblEnterTemperature.setText("Enter Temperature in Farhenheit:");

        lblTemperatureConverted.setText("Celsius: ");

        btnCalculate.setText("Calculate");
        btnCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateActionPerformed(evt);
            }
        });

        btnSwap.setText("Swap!");
        btnSwap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSwapActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblEnterTemperature)
                        .addGap(18, 18, 18)
                        .addComponent(txtTemperatureField))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnSwap, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCalculate, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(lblTemperatureConverted, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTemperatureField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEnterTemperature))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTemperatureConverted)
                    .addComponent(btnCalculate))
                .addGap(18, 18, 18)
                .addComponent(btnSwap)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTemperatureFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTemperatureFieldActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtTemperatureFieldActionPerformed

    private void btnSwapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSwapActionPerformed
        toFahrenheit = !toFahrenheit;
        if(toFahrenheit){
            lblEnterTemperature.setText("Enter Temperature in Celsius:");
            lblTemperatureConverted.setText("Fahrenheit: ");
        }
        else{
            lblEnterTemperature.setText("Enter Temperature in Farhenheit:");
            lblTemperatureConverted.setText("Celsius: "); 
        }
    }//GEN-LAST:event_btnSwapActionPerformed

    private void btnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateActionPerformed
        CelsiusFahrenheitConverter cfc = new CelsiusFahrenheitConverter();
        try{
            double value = Double.parseDouble(txtTemperatureField.getText());
            System.out.println(value);
            double newTemperature;
            if(toFahrenheit){
                newTemperature = cfc.calculateToFahrenheit(value);
                lblTemperatureConverted.setText("Fahrenheit: " + newTemperature);
            }
            else{
                newTemperature = cfc.calculateToCelsius(value);
                lblTemperatureConverted.setText("Celsius: " + newTemperature);             
            }
        }
        catch(NumberFormatException nfe){
            JOptionPane.showMessageDialog(null,"no");
        }
        catch(NullPointerException npe){
            JOptionPane.showMessageDialog(null,"even more no");
        }       

    }//GEN-LAST:event_btnCalculateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CelsiusFarhenheit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CelsiusFarhenheit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CelsiusFarhenheit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CelsiusFarhenheit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CelsiusFarhenheit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalculate;
    private javax.swing.JButton btnSwap;
    private javax.swing.JLabel lblEnterTemperature;
    private javax.swing.JLabel lblTemperatureConverted;
    private javax.swing.JTextField txtTemperatureField;
    // End of variables declaration//GEN-END:variables
    private boolean toFahrenheit = false;
}
