/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guicelsiusfahrenheit;

import java.math.RoundingMode;
import java.text.DecimalFormat;
import java.text.ParseException;
import javax.swing.JOptionPane;

/**
 *
 * @author Alec
 */
public class CelsiusFarhenheit extends javax.swing.JFrame {

    /**
     * Creates new form CelsiusFarhenheit
     */
    public CelsiusFarhenheit() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        txtTemperatureField = new javax.swing.JTextField();
        lblEnterTemperature = new javax.swing.JLabel();
        lblTemperatureConverted = new javax.swing.JLabel();
        btnCalculate = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        rbtnCelsius = new javax.swing.JRadioButton();
        rbtnFahrenheit = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtTemperatureField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTemperatureFieldActionPerformed(evt);
            }
        });

        lblEnterTemperature.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        lblEnterTemperature.setText("Enter Temperature in Farhenheit:");

        lblTemperatureConverted.setText("Celsius: ");

        btnCalculate.setText("Calculate");
        btnCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(0, 0, 0)));

        buttonGroup1.add(rbtnCelsius);
        rbtnCelsius.setSelected(true);
        rbtnCelsius.setText("Celsius");
        rbtnCelsius.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnCelsiusActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtnFahrenheit);
        rbtnFahrenheit.setText("Fahrenheit");
        rbtnFahrenheit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnFahrenheitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbtnCelsius)
                    .addComponent(rbtnFahrenheit))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbtnCelsius)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbtnFahrenheit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblEnterTemperature)
                        .addGap(18, 18, 18)
                        .addComponent(txtTemperatureField, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTemperatureConverted, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCalculate, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTemperatureField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEnterTemperature))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTemperatureConverted))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCalculate)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTemperatureFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTemperatureFieldActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtTemperatureFieldActionPerformed
     /*
        toFahrenheit = !toFahrenheit;
        if(toFahrenheit){
            lblEnterTemperature.setText("Enter Temperature in Celsius:");
            lblTemperatureConverted.setText("Fahrenheit: ");
        }
        else{
            lblEnterTemperature.setText("Enter Temperature in Farhenheit:");
            lblTemperatureConverted.setText("Celsius: "); 
        }
        */
    private void btnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateActionPerformed
        CelsiusFahrenheitConverter cfc = new CelsiusFahrenheitConverter();
        DecimalFormat df = new DecimalFormat("#.##");
        df.setRoundingMode(RoundingMode.CEILING);
        try{
            if(txtTemperatureField.getText() == null || txtTemperatureField.getText() == "" || txtTemperatureField.getText().trim().length() == 0){
                throw new NullPointerException();
            }
            double value = Double.parseDouble(txtTemperatureField.getText());
            double newTemperature;
            if(toFahrenheit){
                newTemperature = cfc.calculateToFahrenheit(value);
                lblTemperatureConverted.setText("Fahrenheit: " + df.format(newTemperature));
            }
            else{
                newTemperature = cfc.calculateToCelsius(value);
                lblTemperatureConverted.setText("Celsius: " + df.format(newTemperature));             
            }
        }
        catch(NumberFormatException nfe){
            JOptionPane.showMessageDialog(null,"Could not parse the number you've entered! Please enter a valid numeric amount!");
            txtTemperatureField.setText("");
        }
        catch(NullPointerException npe){
            JOptionPane.showMessageDialog(null,"Null amount was set for submitting! Use a proper number!");
            txtTemperatureField.setText("");
        }       

    }//GEN-LAST:event_btnCalculateActionPerformed

    private void rbtnCelsiusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnCelsiusActionPerformed
        toFahrenheit = false;
        lblEnterTemperature.setText("Enter Temperature in Farhenheit:");
        lblTemperatureConverted.setText("Celsius: "); 

    }//GEN-LAST:event_rbtnCelsiusActionPerformed

    private void rbtnFahrenheitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnFahrenheitActionPerformed
        toFahrenheit = true;
        lblEnterTemperature.setText("Enter Temperature in Celsius:");
        lblTemperatureConverted.setText("Fahrenheit: ");
    }//GEN-LAST:event_rbtnFahrenheitActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalculate;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblEnterTemperature;
    private javax.swing.JLabel lblTemperatureConverted;
    private javax.swing.JRadioButton rbtnCelsius;
    private javax.swing.JRadioButton rbtnFahrenheit;
    private javax.swing.JTextField txtTemperatureField;
    // End of variables declaration//GEN-END:variables
    private boolean toFahrenheit = false;
}
